/** Declaration file generated by dts-gen */

export = xlsx_populate_wrapper;

declare class xlsx_populate_wrapper {
    constructor(...args: any[]);

    data(...args: any[]): void;

    init(...args: any[]): void;

    update(...args: any[]): void;

    worksheet(...args: any[]): void;

    worksheetNames(...args: any[]): void;

    static convertJson(...args: any[]): void;

}

declare namespace xlsx_populate_wrapper {
    namespace prototype {
        function data(...args: any[]): void;

        function init(...args: any[]): void;

        function update(...args: any[]): void;

        function worksheet(...args: any[]): void;

        function worksheetNames(...args: any[]): void;

    }

}

